### ISSUE TITLE
Upgrading failes during cache:clear

### ISSUE THREAD

**Issue by xentity** [kevinpapst/kimai2#1152]
**Describe the bug**
During the upgrade to 1.3 the script fails with:

`Generating optimized autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "WebServerBundle" from namespace "Symfony\Bundle\WebServerBundle".
!!  Did you forget a "use" statement for another namespace? in /opt/kimai2/src/Kernel.php:85
!!  Stack trace:
!!  #0 /opt/kimai2/vendor/symfony/http-kernel/Kernel.php(424): App\Kernel->registerBundles()
!!  #1 /opt/kimai2/vendor/symfony/http-kernel/Kernel.php(130): Symfony\Component\HttpKernel\Kernel->initializeBundles()
!!  #2 /opt/kimai2/vendor/symfony/framework-bundle/Console/Application.php(159): Symfony\Component\HttpKernel\Kernel->boot()
!!  #3 /opt/kimai2/vendor/symfony/framework-bundle/Console/Application.php(65): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
!!  #4 /opt/kimai2/vendor/symfony/console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
!!  #5 /opt/kimai2/bin/console(39): Symfony\Component\Console\Applicat in /opt/kimai2/src/Kernel.php on line 85
!!  
Script @auto-scripts was called via post-install-cmd
`
If I recheck out 1.1 it works and can access kimai2, again. The same happens with 1.2

**To Reproduce**
1. checkout 1.3
2. run composer install --no-dev --optimize-autoloader
3. See error

**Additional context**
- Kimai2 1.1 --> 1.2/1.3
- Ubuntu 18.04.3
- PHP 7.2.19

**Comment by kevinpapst** [comment]
Are you running in "APP_ENV=dev" mode? If so, you need to install the dev packages as well.

**Comment by xentity** [comment]
Not bad :-) Changed it to prod, now.

Just out of curiosity: what would be the steps for "install the dev packages"? I guess, you do not mean the php dev packages, don't you?

And, last but not least:

```
$ sudo -u www-data bin/console doctrine:migrations:migrate
                                                              
                    Application Migrations                    
                                                              

WARNING! You are about to execute a database migration that could result in schema changes and data loss. Are you sure you wish to continue? (y/n)y
Migrating up to 20190813162649 from 0

  ++ migrating 20180701120000

     -> CREATE TABLE kimai2_users (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(60) NOT NULL, mail VARCHAR(160) NOT NULL, password VARCHAR(254) DEFAULT NULL, alias VARCHAR(60) DEFAULT NULL, active TINYINT(1) NOT NULL, registration_date DATETIME DEFAULT NULL, title VARCHAR(50) DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL COMMENT '(DC2Type:json_array)', UNIQUE INDEX UNIQ_B9AC5BCE5E237E06 (name), UNIQUE INDEX UNIQ_B9AC5BCE5126AC48 (mail), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB
Migration 20180701120000 failed during Execution. Error An exception occurred while executing 'CREATE TABLE kimai2_users (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(60) NOT NULL, mail VARCHAR(160) NOT NULL, password VARCHAR(254) DEFAULT NULL, alias VARCHAR(60) DEFAULT NULL, active TINYINT(1) NOT NULL, registration_date DATETIME DEFAULT NULL, title VARCHAR(50) DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL COMMENT '(DC2Type:json_array)', UNIQUE INDEX UNIQ_B9AC5BCE5E237E06 (name), UNIQUE INDEX UNIQ_B9AC5BCE5126AC48 (mail), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB':

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'kimai2_users' already exists
14:14:22 ERROR     [console] Error thrown while running command "doctrine:migrations:migrate". Message: "An exception occurred while executing 'CREATE TABLE kimai2_users (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(60) NOT NULL, mail VARCHAR(160) NOT NULL, password VARCHAR(254) DEFAULT NULL, alias VARCHAR(60) DEFAULT NULL, active TINYINT(1) NOT NULL, registration_date DATETIME DEFAULT NULL, title VARCHAR(50) DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL COMMENT '(DC2Type:json_array)', UNIQUE INDEX UNIQ_B9AC5BCE5E237E06 (name), UNIQUE INDEX UNIQ_B9AC5BCE5126AC48 (mail), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB':\n\nSQLSTATE[42S01]: Base table or view already exists: 1050 Table 'kimai2_users' already exists" ["exception" => Doctrine\DBAL\Exception\TableExistsException^ { …},"command" => "doctrine:migrations:migrate","message" => """  An exception occurred while executing 'CREATE TABLE kimai2_users (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(60) NOT NULL, mail VARCHAR(160) NOT NULL, password VARCHAR(254) DEFAULT NULL, alias VARCHAR(60) DEFAULT NULL, active TINYINT(1) NOT NULL, registration_date DATETIME DEFAULT NULL, title VARCHAR(50) DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL COMMENT '(DC2Type:json_array)', UNIQUE INDEX UNIQ_B9AC5BCE5E237E06 (name), UNIQUE INDEX UNIQ_B9AC5BCE5126AC48 (mail), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB':\n  \n  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'kimai2_users' already exists  """]

In AbstractMySQLDriver.php line 38:
                                                                                                                                                                                                           
  An exception occurred while executing 'CREATE TABLE kimai2_users (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(60) NOT NULL, mail VARCHAR(160) NOT NULL, password VARCHAR(254) DEFAULT NULL, alias VARC  
  HAR(60) DEFAULT NULL, active TINYINT(1) NOT NULL, registration_date DATETIME DEFAULT NULL, title VARCHAR(50) DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL COMMENT '(DC2Type:json  
  _array)', UNIQUE INDEX UNIQ_B9AC5BCE5E237E06 (name), UNIQUE INDEX UNIQ_B9AC5BCE5126AC48 (mail), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB':              
                                                                                                                                                                                                           
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'kimai2_users' already exists                                                                                                             
                                                                                                                                                                                                           

In PDOConnection.php line 90:
                                                                                                
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'kimai2_users' already exists  
                                                                                                

In PDOConnection.php line 88:
                                                                                                
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'kimai2_users' already exists  

```

I guess, the problem is based on this: `Migrating up to 20190813162649 from 0` . The schema was created by the migration script kimai1-->kimai2 1.1 . How can I set the correct schema value?

**Comment by kevinpapst** [comment]
Skip `--no-dev`: `composer install --optimize-autoloader`

If you migrated from the 1.1 release, then you must declare all Migrations from that release as imported: https://github.com/kevinpapst/kimai2/tree/1.1/src/Migrations
Thats done in the normal installation process, you skipped that step obviously.

Try this: 
```
bin/console doctrine:migrations:version --add --range-from=20180701120000 --range-to=20190706224219
```

And then run the migrations again.

**Comment by xentity** [comment]
Perfect! Works like a charm!
