### ISSUE TITLE
invalid "kimai" configuration: Unrecognized option "user" under "kimai.defaults"

### ISSUE THREAD

**Issue by jacoblanco** [kevinpapst/kimai2#1176]
**Describe the bug**
Set defaults to "user preferences" under local.yaml following documentation
https://www.kimai.org/documentation/user-preferences.html

**To Reproduce**
1. Edit local.yaml and add following:
    defaults:
        user:
            timezone: Europe/London
            language: de
            theme: purple

**Logfile**
```
Notice: Found invalid "kimai" configuration: Unrecognized option "user" under "kimai.defaults". Available option is "customer". in /opt/kimai/src/DependencyInjection/AppExtension.php on line 31

Fatal error: Uncaught Symfony\Component\Config\Definition\Exception\InvalidConfigurationException: Unrecognized option "user" under "kimai.defaults". Available option is "customer". in /opt/kimai/vendor/symfony/config/Definition/ArrayNode.php:331 Stack trace: #0 /opt/kimai/vendor/symfony/config/Definition/BaseNode.php(363): Symfony\Component\Config\Definition\ArrayNode->normalizeValue(Array) #1 /opt/kimai/vendor/symfony/config/Definition/ArrayNode.php(296): Symfony\Component\Config\Definition\BaseNode->normalize(Array) #2 /opt/kimai/vendor/symfony/config/Definition/BaseNode.php(363): Symfony\Component\Config\Definition\ArrayNode->normalizeValue(Array) #3 /opt/kimai/vendor/symfony/config/Definition/Processor.php(35): Symfony\Component\Config\Definition\BaseNode->normalize(Array) #4 /opt/kimai/vendor/symfony/config/Definition/Processor.php(52): Symfony\Component\Config\Definition\Processor->process(Object(Symfony\Component\Config\Definition\ArrayNode), Array) #5 /opt/kimai/vendor/symfony/dependency-injection/Extension/Exten in /opt/kimai/vendor/symfony/config/Definition/ArrayNode.php on line 331
```

**Additional context**
Users are imported from LDAP.

 - Kimai version: Kimai 2 - 0.9 stable (Ayumi) 
 - PHP version  7.2.9

**Comment by kevinpapst** [comment]
0.9 was released half a year ago. Maybe the settings wasn't existing back then.
You need to upgrade to a recent version.
