### ISSUE TITLE
update problems on plesk

### ISSUE THREAD

**Issue by BKapelari** [kevinpapst/kimai2#1202]
**Describe the bug**
I did the update as in the [docs](https://www.kimai.org/documentation/updates.html) explaind.

**what I did**
1. git fetch --tags
2. git checkout 1.4.2
3. because I'm on a plesk server I have to declare the path to composer. so I did: sudo -u www.data /opt/plesk/php/7.3/bin/php /usr/lib/plesk-9.0/composer.phar install --no-dev --optimize-autoloader

**output**
```
Cannot create cache directory /root/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /root/.composer/cache/files/, or directory is not writable. Proceeding without cache
Cannot create cache directory /root/.composer/cache/repo/https---flex.symfony.com/, or directory is not writable. Proceeding without cache
Cannot create cache directory /root/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /root/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  PHP Warning:  include_once(/var/www/vhosts/kimai2/src/Command/ConvertTimezoneCommand.php): failed to open stream: No such file or directory in /var/www/vhosts/kimai2/var/cache/prod/ContainerGAwuOqt/getConvertTimezoneCommandService.php on line 10
!!  PHP Warning:  include_once(): Failed opening '/var/www/vhosts/kimai2/src/Command/ConvertTimezoneCommand.php' for inclusion (include_path='.:/opt/plesk/php/7.3/share/pear') in /var/www/vhosts/kimai2/var/cache/prod/ContainerGAwuOqt/getConvertTimezoneCommandService.php on line 10
!!  PHP Warning:  include_once(/var/www/vhosts/kimai2/vendor/symfony/security/Core/Encoder/UserPasswordEncoderInterface.php): failed to open stream: No such file or directory in /var/www/vhosts/kimai2/var/cache/prod/ContainerGAwuOqt/getSecurity_PasswordEncoderService.php on line 9
!!  PHP Warning:  include_once(): Failed opening '/var/www/vhosts/kimai2/vendor/symfony/security/Core/Encoder/UserPasswordEncoderInterface.php' for inclusion (include_path='.:/opt/plesk/php/7.3/share/pear') in /var/www/vhosts/kimai2/var/cache/prod/ContainerGAwuOqt/getSecurity_PasswordEncoderService.php on line 9
!!  PHP Warning:  include_once(/var/www/vhosts/kimai2/vendor/symfony/security/Core/Encoder/UserPasswordEncoder.php): failed to open stream: No such file or directory in /var/www/vhosts/kimai2/var/cache/prod/ContainerGAwuOqt/getSecurity_PasswordEncoderService.php on line 10
!!  PHP Warning:  include_once(): Failed opening '/var/www/vhosts/kimai2/vendor/symfony/security/Core/Encoder/UserPasswordEncoder.php' for inclusion (include_path='.:/opt/plesk/php/7.3/share/pear') in /var/www/vhosts/kimai2/var/cache/prod/ContainerGAwuOqt/getSecurity_PasswordEncoderService.php on line 10
!!
!!
!!   [WARNING] Some commands could not be registered:
!!
!!
!!  In getConvertTimezoneCommandService.php line 12:
!!
!!    Class 'App\Command\ConvertTimezoneCommand' not found
!!
!!
!!
!!
!!   [WARNING] Some commands could not be registered:
!!
!!
!!  In getConvertTimezoneCommandService.php line 12:
!!
!!    Class 'App\Command\ConvertTimezoneCommand' not found
!!
!!
!!
!!   // Clearing the cache for the prod environment with debug
!!   // false
!!
!!
!!  In Filesystem.php line 181:
!!
!!    Failed to remove directory "/var/www/vhosts/kimai2/var/cache/pro_/jms_serializer": rmdir(/var/www/kimai2/var/cache/pro_/jms_serializer): Permission deni
!!    ed.
!!
!!
!!  cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
!!
!!
Script @auto-scripts was called via post-install-cmd
```

** logfile **
```
[2019-10-29 10:41:16] php.INFO: User Deprecated: Option "generator_base_class" given to router Symfony\Bundle\FrameworkBundle\Routing\Router is deprecated since Symfony 4.3. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Option \"generator_base_class\" given to router Symfony\\Bundle\\FrameworkBundle\\Routing\\Router is deprecated since Symfony 4.3. at /var/www/vhosts/kimai2/vendor/symfony/routing/Router.php:430)"} []
[2019-10-29 10:41:16] php.INFO: User Deprecated: Option "generator_cache_class" given to router Symfony\Bundle\FrameworkBundle\Routing\Router is deprecated since Symfony 4.3. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Option \"generator_cache_class\" given to router Symfony\\Bundle\\FrameworkBundle\\Routing\\Router is deprecated since Symfony 4.3. at /var/www/vhosts/kimai2/vendor/symfony/routing/Router.php:430)"} []
[2019-10-29 10:41:16] php.INFO: User Deprecated: Option "matcher_base_class" given to router Symfony\Bundle\FrameworkBundle\Routing\Router is deprecated since Symfony 4.3. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Option \"matcher_base_class\" given to router Symfony\\Bundle\\FrameworkBundle\\Routing\\Router is deprecated since Symfony 4.3. at /var/www/vhosts/kimai2/vendor/symfony/routing/Router.php:430)"} []
[2019-10-29 10:41:16] php.INFO: User Deprecated: Option "matcher_cache_class" given to router Symfony\Bundle\FrameworkBundle\Routing\Router is deprecated since Symfony 4.3. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Option \"matcher_cache_class\" given to router Symfony\\Bundle\\FrameworkBundle\\Routing\\Router is deprecated since Symfony 4.3. at /var/www/vhosts/kimai2/vendor/symfony/routing/Router.php:430)"} []
[2019-10-29 10:41:16] php.INFO: User Deprecated: The "Symfony\Bundle\FrameworkBundle\Routing\RedirectableUrlMatcher" class is deprecated since Symfony 4.3. {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"Symfony\\Bundle\\FrameworkBundle\\Routing\\RedirectableUrlMatcher\" class is deprecated since Symfony 4.3. at /var/www/vhosts/kimai2/vendor/symfony/framework-bundle/Routing/RedirectableUrlMatcher.php:14)"} []
[2019-10-29 10:41:16] php.CRITICAL: Fatal Error: Trait 'Symfony\Component\Routing\Matcher\Dumper\PhpMatcherTrait' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Trait 'Symfony\\Component\\Routing\\Matcher\\Dumper\\PhpMatcherTrait' not found at /var/www/vhosts/kimai2/var/cache/prod/srcApp_KernelProdContainerUrlMatcher.php:12)"} []
[2019-10-29 10:41:20] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load trait "PhpMatcherTrait" from namespace "Symfony\Component\Routing\Matcher\Dumper". Did you forget a "use" statement for another namespace?" at /var/www/vhosts/kimai2/var/cache/prod/srcApp_KernelProdContainerUrlMatcher.php line 12 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load trait \"PhpMatcherTrait\" from namespace \"Symfony\\Component\\Routing\\Matcher\\Dumper\".\nDid you forget a \"use\" statement for another namespace? at /var/www/vhosts/kimai2/var/cache/prod/srcApp_KernelProdContainerUrlMatcher.php:12)"} []
[2019-10-29 10:41:20] php.INFO: User Deprecated: Passing a "Symfony\Component\HttpFoundation\RequestStack" instance as the first argument to the "Symfony\Bridge\Twig\Extension\HttpFoundationExtension" constructor is deprecated since Symfony 4.3, pass a "Symfony\Component\HttpFoundation\UrlHelper" instance instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Passing a \"Symfony\\Component\\HttpFoundation\\RequestStack\" instance as the first argument to the \"Symfony\\Bridge\\Twig\\Extension\\HttpFoundationExtension\" constructor is deprecated since Symfony 4.3, pass a \"Symfony\\Component\\HttpFoundation\\UrlHelper\" instance instead. at /var/www/vhosts/kimai2/vendor/symfony/twig-bridge/Extension/HttpFoundationExtension.php:45)"} []
[2019-10-29 10:41:20] php.CRITICAL: Too few arguments to function App\Widget\Type\DailyWorkingTimeChart::__construct(), 2 passed in /var/www/vhosts/kimai2/var/cache/prod/ContainerGAwuOqt/srcApp_KernelProdContainer.php on line 1350 and exactly 3 expected {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Too few arguments to function App\\Widget\\Type\\DailyWorkingTimeChart::__construct(), 2 passed in /var/www/vhosts/kimai2/var/cache/prod/ContainerGAwuOqt/srcApp_KernelProdContainer.php on line 1350 and exactly 3 expected at /var/www/vhosts/kimai2/src/Widget/Type/DailyWorkingTimeChart.php:30)"} []
```

**Additional context**
 - Kimai2 v1.1
 - 7.3

**Comment by kevinpapst** [comment]
Delete all contents in `/var/www/kimai2/var/cache/` manually (there should be a prod/ directory, remove it).
Then run the composer call again.

**Comment by BKapelari** [comment]
@kevinpapst Thank you for your prompt reply!
now I got the following errors: 

```
Cannot create cache directory /root/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /root/.composer/cache/files/, or directory is not writable. Proceeding without cache
Cannot create cache directory /root/.composer/cache/repo/https---flex.symfony.com/, or directory is not writable. Proceeding without cache
Cannot create cache directory /root/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /root/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Uncaught Error: Class 'App\Event\ConfigureAdminMenuEvent' not found in /var/www/vhosts/kimai2/var/plugins/CustomCSSBundle/EventSubscriber/MenuSubscriber.php:39
!!  Stack trace:
!!  #0 /var/www/vhosts/kimai2/vendor/symfony/event-dispatcher/DependencyInjection/RegisterListenersPass.php(146): KimaiPlugin\CustomCSSBundle\EventSubscriber\MenuSubscriber::getSubscribedEvents()
!!  #1 /var/www/vhosts/kimai2/vendor/symfony/event-dispatcher/EventDispatcher.php(193): Symfony\Component\EventDispatcher\DependencyInjection\ExtractingEventDispatcher::getSubscribedEvents()
!!  #2 /var/www/vhosts/kimai2/vendor/symfony/event-dispatcher/DependencyInjection/RegisterListenersPass.php(112): Symfony\Component\EventDispatcher\EventDispatcher->addSubscriber(Object(Symfony\Component\EventDispatcher\DependencyInjection\ExtractingEventDispatcher))
!!  #3 /var/www/vhosts/kimai2/vendor/symfony/de in /var/www/vhosts/kimai2/var/plugins/CustomCSSBundle/EventSubscriber/MenuSubscriber.php on line 39
!!
Script @auto-scripts was called via post-install-cmd
```

**Comment by kevinpapst** [comment]
You need to update your plugins as well. After that clear the cache once again ;-)

**Comment by BKapelari** [comment]
now I got this:
```
root@kapelari:/var/www/vhosts/kimai2# sudo -u kapelari-kg /opt/plesk/php/7.3/bin/php /usr/lib/plesk-9.0/composer.phar install --no-dev --optimize-autoloader
Cannot create cache directory /root/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /root/.composer/cache/files/, or directory is not writable. Proceeding without cache
Cannot create cache directory /root/.composer/cache/repo/https---flex.symfony.com/, or directory is not writable. Proceeding without cache
Cannot create cache directory /root/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /root/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!   // Clearing the cache for the prod environment with debug
!!   // false
!!
!!
!!  In Filesystem.php line 181:
!!
!!    Failed to remove directory "/var/www/vhosts/kimai2/var/cache/pro_/jms_serializer": rmdir(/var/www/vhosts/kimai2/var/cache/pro_/jms_serializer): Permission deni
!!    ed.
!!
!!
!!  cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
!!
!!
Script @auto-scripts was called via post-install-cmd
```
I tried the database update:

```
                    Application Migrations

WARNING! You are about to execute a database migration that could result in schema changes and data loss. Are you sure you wish to continue? (y/n)y
Migrating up to 20190813162649 from 20190706224211

  ++ migrating 20190706224219 (Creates several indices to improve speed for default queries.)

Migration 20190706224219 failed during Execution. Error An index with name 'idx_8811fe1c7ab0e859166d1f9c' was already defined on table 'kimai2_activities'.
12:16:36 ERROR     [console] Error thrown while running command "doctrine:migrations:migrate". Message: "An index with name 'idx_8811fe1c7ab0e859166d1f9c' was already defined on table 'kimai2_activities'." ["exception" => Doctrine\DBAL\Schema\SchemaException^ { …},"command" => "doctrine:migrations:migrate","message" => "An index with name 'idx_8811fe1c7ab0e859166d1f9c' was already defined on table 'kimai2_activities'."]

In SchemaException.php line 68:

  An index with name 'idx_8811fe1c7ab0e859166d1f9c' was already defined on table 'kimai2_activities'.
doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--db DB] [--em EM] [--shard SHARD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<version>]
```

In the UI i get a error 500.

**Comment by kevinpapst** [comment]
1. delete all cache directories again
2. Execute this sql
```
insert into migration_versions (version, executed_at) values ('20190706224219', now());
```
3. run the migrations afterwards

**Comment by BKapelari** [comment]
# Perfect! Now everything works again!
Thank you for your awesome work. I've used Kimai v1 years ago and I like the v2 even more!
