### ISSUE TITLE
 Error importing v1 Database (could not convert to string)

### ISSUE THREAD

**Issue by MMetze** [kevinpapst/kimai2#431]
**Describe the bug**
Migration of DB in Kimai2 0.6
While importing Kimai 1.1.0 database, the following error occures:
```
Importing timesheets, please wait
[ERROR] Failed to import timesheet records: Catchable Fatal Error: Object of class App\Entity\Timesheet could not beconverted to string
```

**To Reproduce**
running the import on local server

**Expected behavior**
Migrating the v1 database to my v2 installation

**Server**
OS: Ubuntu 16.04.5 LTS
mySQL: 5.7.24

**Comment by kevinpapst** [comment]
I hope you don't get annoyed, but you might run into more problems. 
Not many people used the importer by now and Kimai v1 has a buggy database structure that sometimes creates corrupt data.
Could you adjust the importer again so we can try to find the reason [by adjusting this line](https://github.com/kevinpapst/kimai2/blob/master/src/Command/KimaiImporterCommand.php#L290)
```
            $io->error('Failed to import timesheet records: ' . $ex->getMessage() . PHP_EOL . $ex->getTraceAsString());
```

**Comment by MMetze** [comment]
No worries. I love kimai and I'm happy to help.
If you need someone with a production environment to run tests against, just shoot me a message.
```
[ERROR] Failed to import timesheet records: Catchable Fatal Error: Object of class App\Entity\Timesheet could not be
         converted to string
         #0 /var/www/html/kimai2/src/Command/KimaiImporterCommand.php(943):
         App\Command\KimaiImporterCommand->validateImport(Object(Symfony\Component\Console\Style\SymfonyStyle),
         Object(App\Entity\Timesheet))
         #1 /var/www/html/kimai2/src/Command/KimaiImporterCommand.php(286):
         App\Command\KimaiImporterCommand->importTimesheetRecords(Object(Symfony\Component\Console\Style\SymfonyStyle),
         Array, Array, Array)
         #2 /var/www/html/kimai2/vendor/symfony/console/Command/Command.php(255):
         App\Command\KimaiImporterCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput),
         Object(Symfony\Component\Console\Output\ConsoleOutput))
         #3 /var/www/html/kimai2/vendor/symfony/console/Application.php(904):
         Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput),
         Object(Symfony\Component\Console\Output\ConsoleOutput))
         #4 /var/www/html/kimai2/vendor/symfony/framework-bundle/Console/Application.php(89):
         Symfony\Component\Console\Application->doRunCommand(Object(App\Command\KimaiImporterCommand),
         Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
         #5 /var/www/html/kimai2/vendor/symfony/console/Application.php(262):
         Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(App\Command\KimaiImporterCommand),
         Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
         #6 /var/www/html/kimai2/vendor/symfony/framework-bundle/Console/Application.php(75):
         Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput),
         Object(Symfony\Component\Console\Output\ConsoleOutput))
         #7 /var/www/html/kimai2/vendor/symfony/console/Application.php(145):
         Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput),
         Object(Symfony\Component\Console\Output\ConsoleOutput))
         #8 /var/www/html/kimai2/bin/console(39):
         Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
         #9 {main}

```

**Comment by kevinpapst** [comment]
Okay, the error seems to be in `protected function validateImport(SymfonyStyle $io, $object)`.
Can you try to replace the function with the updated version:
```
    protected function validateImport(SymfonyStyle $io, $object)
    {
        $errors = $this->validator->validate($object);

        if ($errors->count() > 0) {
            /** @var \Symfony\Component\Validator\ConstraintViolation $error */
            foreach ($errors as $error) {
                $value = $error->getInvalidValue();

                if (is_array($value)) {
                    $value = implode(',', $value);
                } elseif (is_object($value)) {
                    $value = get_class($value);
                }

                $io->error(
                    $error->getPropertyPath()
                    . ' (' . $value . ')'
                    . "\n    "
                    . $error->getMessage()
                );
            }

            return false;
        }

        return true;
    }
```

**Comment by MMetze** [comment]
Sure:
```
Importing timesheets, please wait


 [ERROR] activity (App\Entity\Timesheet)
             Cannot start a disabled activity.



 [ERROR] Failed to import timesheet records: Failed to validate timesheet record:
         #0 /var/www/html/kimai2/src/Command/KimaiImporterCommand.php(286):
         App\Command\KimaiImporterCommand->importTimesheetRecords(Object(Symfony\Component\Console\Style\SymfonyStyle),
         Array, Array, Array)
         #1 /var/www/html/kimai2/vendor/symfony/console/Command/Command.php(255):
         App\Command\KimaiImporterCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput),
         Object(Symfony\Component\Console\Output\ConsoleOutput))
         #2 /var/www/html/kimai2/vendor/symfony/console/Application.php(904):
         Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput),
         Object(Symfony\Component\Console\Output\ConsoleOutput))
         #3 /var/www/html/kimai2/vendor/symfony/framework-bundle/Console/Application.php(89):
         Symfony\Component\Console\Application->doRunCommand(Object(App\Command\KimaiImporterCommand),
         Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
         #4 /var/www/html/kimai2/vendor/symfony/console/Application.php(262):
         Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(App\Command\KimaiImporterCommand),
         Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
         #5 /var/www/html/kimai2/vendor/symfony/framework-bundle/Console/Application.php(75):
         Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput),
         Object(Symfony\Component\Console\Output\ConsoleOutput))
         #6 /var/www/html/kimai2/vendor/symfony/console/Application.php(145):
         Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput),
         Object(Symfony\Component\Console\Output\ConsoleOutput))
         #7 /var/www/html/kimai2/bin/console(39):
         Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
         #8 {main}
```

**Comment by kevinpapst** [comment]
Okay, two things: 
First is just for me ;-) could you try it again with 
```
    protected function validateImport(SymfonyStyle $io, $object)
    {
        $errors = $this->validator->validate($object);

        if ($errors->count() > 0) {
            /** @var \Symfony\Component\Validator\ConstraintViolation $error */
            foreach ($errors as $error) {
                $io->error(
                    (string) $error
                );
            }

            return false;
        }

        return true;
    }
```
just to see if the error message is more readable.

The other message is a new validation message I added in 0.6 - seems it does not work properly. I'll post the needed update in a minute.

**Comment by MMetze** [comment]
First, just for you:
```
 [ERROR] Object(App\Entity\Timesheet).activity:
             Cannot start a disabled activity.



 [ERROR] Failed to import timesheet records: Failed to validate timesheet record:
         #0 /var/www/html/kimai2/src/Command/KimaiImporterCommand.php(286):
         App\Command\KimaiImporterCommand->importTimesheetRecords(Object(Symfony\Component\Console\Style\SymfonyStyle),
         Array, Array, Array)
         #1 /var/www/html/kimai2/vendor/symfony/console/Command/Command.php(255):
         App\Command\KimaiImporterCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput),
         Object(Symfony\Component\Console\Output\ConsoleOutput))
         #2 /var/www/html/kimai2/vendor/symfony/console/Application.php(904):
         Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput),
         Object(Symfony\Component\Console\Output\ConsoleOutput))
         #3 /var/www/html/kimai2/vendor/symfony/framework-bundle/Console/Application.php(89):
         Symfony\Component\Console\Application->doRunCommand(Object(App\Command\KimaiImporterCommand),
         Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
         #4 /var/www/html/kimai2/vendor/symfony/console/Application.php(262):
         Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(App\Command\KimaiImporterCommand),
         Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
         #5 /var/www/html/kimai2/vendor/symfony/framework-bundle/Console/Application.php(75):
         Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput),
         Object(Symfony\Component\Console\Output\ConsoleOutput))
         #6 /var/www/html/kimai2/vendor/symfony/console/Application.php(145):
         Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput),
         Object(Symfony\Component\Console\Output\ConsoleOutput))
         #7 /var/www/html/kimai2/bin/console(39):
         Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
         #8 {main}
```

**Comment by kevinpapst** [comment]
Looks better, thanks 👍 

The error is in the Timesheet class ... I hope this is the last problem ;-)

Please replace this method:
https://github.com/kevinpapst/kimai2/blob/master/src/Entity/Timesheet.php#L355
with:
```
    public function validate(ExecutionContextInterface $context, $payload)
    {
        if (null === ($activity = $this->getActivity())) {
            $context->buildViolation('A timesheet must have an activity.')
                ->atPath('activity')
                ->setTranslationDomain('validators')
                ->addViolation();
        }

        if (null === ($project = $this->getProject())) {
            $context->buildViolation('A timesheet must have a project.')
                ->atPath('project')
                ->setTranslationDomain('validators')
                ->addViolation();
        }

        if (null !== $activity && null !== $project) {
            if (null !== $activity->getProject() && $activity->getProject() !== $project) {
                $context->buildViolation('Project mismatch, project specific activity and timesheet project are different.')
                    ->atPath('project')
                    ->setTranslationDomain('validators')
                    ->addViolation();
            }

            if (null === $this->getEnd() && $activity->getVisible() === false) {
                $context->buildViolation('Cannot start a disabled activity.')
                    ->atPath('activity')
                    ->setTranslationDomain('validators')
                    ->addViolation();
            }

            if (null === $this->getEnd() && $project->getVisible() === false) {
                $context->buildViolation('Cannot start a disabled project.')
                    ->atPath('project')
                    ->setTranslationDomain('validators')
                    ->addViolation();
            }

            if (null === $this->getEnd() && $project->getCustomer()->getVisible() === false) {
                $context->buildViolation('Cannot start a disabled customer.')
                    ->atPath('customer')
                    ->setTranslationDomain('validators')
                    ->addViolation();
            }
        }

        if (null === $this->getBegin() && null !== $this->getEnd()) {
            $context->buildViolation('You must submit a begin date before an end date is added.')
                ->atPath('begin')
                ->setTranslationDomain('validators')
                ->addViolation();
        }

        if (null !== $this->getBegin() && null !== $this->getEnd() && $this->getEnd()->getTimestamp() < $this->getBegin()->getTimestamp()) {
            $context->buildViolation('End date must not be earlier then start date.')
                ->atPath('end')
                ->setTranslationDomain('validators')
                ->addViolation();
        }
    }
```

**Comment by MMetze** [comment]
I don't know yet if this is related or a new thing. Or maybe my fault in setting it up:
```
[Mon Nov 19 01:27:56.040446 2018] [:error] [pid 23859] [client 192.168.42.68:51238] PHP Fatal error:  Uncaught TypeError: Return value of Symfony\\Component\\Dotenv\\Dotenv::populate() must be an instance of Symfony\\Component\\Dotenv\\void, none returned in /var/www/html/kimai2/vendor/symfony/dotenv/Dotenv.php:95\nStack trace:\n#0 /var/www/html/kimai2/vendor/symfony/dotenv/Dotenv.php(57): Symfony\\Component\\Dotenv\\Dotenv->populate(Array)\n#1 /var/www/html/kimai2/public/index.php(15): Symfony\\Component\\Dotenv\\Dotenv->load('/var/www/html/k...')\n#2 {main}\n  thrown in /var/www/html/kimai2/vendor/symfony/dotenv/Dotenv.php on line 95

```

**Comment by kevinpapst** [comment]
That message is new to me, but I don't think it relates to the import. Do you have the `.env` file?

**Comment by MMetze** [comment]
Yes.
Could be something related to my php7.1 installation.
```
# This file is a "template" of which env vars need to be defined for your application
# Copy this file to .env file for development, create environment variables when deploying to production
# https://symfony.com/doc/current/best_practices/configuration.html#infrastructure-related-configuration

# KIMAI DEFAULT ENV VARS
DATABASE_PREFIX=kimai_
MAILER_FROM=***@***

###> symfony/framework-bundle ###
APP_ENV=prod
APP_SECRET=***
#TRUSTED_PROXIES=127.0.0.1,127.0.0.2
#TRUSTED_HOSTS=localhost,example.com
###< symfony/framework-bundle ###

###> doctrine/doctrine-bundle ###
# Format described at http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#connecting-using-a-url
# For an SQLite database, use: "sqlite:///%kernel.project_dir%/var/data/kimai.sqlite"
# Configure your db driver and server_version in config/packages/doctrine.yaml
 DATABASE_URL=mysql://kimai:***@127.0.0.1:3306/kimai
#DATABASE_URL=sqlite:///%kernel.project_dir%/var/data/kimai.sqlite
###< doctrine/doctrine-bundle ###

###> symfony/swiftmailer-bundle ###
# For Gmail as a transport, use: "gmail://username:password@localhost"
# For a generic SMTP server, use: "smtp://localhost:25?encryption=&auth_mode="
# Delivery is disabled by default via "null://localhost"
MAILER_URL=null://localhost
###< symfony/swiftmailer-bundle ###
```

**Comment by MMetze** [comment]
It seems that apache is still using php7.0*

**Comment by kevinpapst** [comment]
That could be the reason, but I can't verify that right now. But I'll add it to the FAQ if thats the reason.

**Comment by MMetze** [comment]
It was.
I upgraded my ubuntu installation and ```a2enmod php7.1``` but I did not ```a2dismod php7.0```
