### ISSUE TITLE
Fresh install leads to missing Class

### ISSUE THREAD

**Issue by Mikesch-mp** [kevinpapst/kimai2#954]
**Describe the bug**
With a fresh installation i get a missing Class error, no matter if run as apache user or as root.

```
[root@kimai2 kimai2]# composer install --no-dev --optimize-autoloader
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 136 installs, 0 updates, 0 removals
  - Installing ocramius/package-versions (1.4.0): Downloading (100%)
  - Installing kimai/kimai2-composer (0.1): Downloading (100%)
  - Installing symfony/flex (v1.4.1): Downloading (100%)

Prefetching 133 packages 🎶 💨
  - Downloading (100%)

  - Installing beberlei/doctrineextensions (v1.2.2): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.11.0): Loading from cache
  - Installing symfony/polyfill-ctype (v1.11.0): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing psr/cache (1.0.1): Loading from cache
  - Installing symfony/contracts (v1.1.5): Loading from cache
  - Installing doctrine/lexer (1.0.2): Loading from cache
  - Installing doctrine/annotations (v1.6.1): Loading from cache
  - Installing doctrine/reflection (v1.0.0): Loading from cache
  - Installing doctrine/event-manager (v1.0.0): Loading from cache
  - Installing doctrine/collections (v1.6.2): Loading from cache
  - Installing doctrine/cache (v1.8.0): Loading from cache
  - Installing doctrine/persistence (1.1.1): Loading from cache
  - Installing symfony/doctrine-bridge (v4.2.10): Loading from cache
  - Installing doctrine/inflector (v1.3.0): Loading from cache
  - Installing doctrine/doctrine-cache-bundle (1.3.5): Loading from cache
  - Installing symfony/routing (v4.2.10): Loading from cache
  - Installing symfony/http-foundation (v4.2.10): Loading from cache
  - Installing symfony/event-dispatcher (v4.2.10): Loading from cache
  - Installing psr/log (1.1.0): Loading from cache
  - Installing symfony/debug (v4.2.10): Loading from cache
  - Installing symfony/http-kernel (v4.2.10): Loading from cache
  - Installing symfony/finder (v4.2.10): Loading from cache
  - Installing symfony/filesystem (v4.2.10): Loading from cache
  - Installing symfony/dependency-injection (v4.2.10): Loading from cache
  - Installing symfony/config (v4.2.10): Loading from cache
  - Installing symfony/var-exporter (v4.2.10): Loading from cache
  - Installing psr/simple-cache (1.0.1): Loading from cache
  - Installing symfony/cache (v4.2.10): Loading from cache
  - Installing symfony/framework-bundle (v4.2.10): Loading from cache
  - Installing symfony/console (v4.2.10): Loading from cache
  - Installing doctrine/instantiator (1.2.0): Loading from cache
  - Installing doctrine/dbal (v2.9.2): Loading from cache
  - Installing doctrine/common (v2.10.0): Loading from cache
  - Installing doctrine/orm (v2.6.3): Loading from cache
  - Installing jdorn/sql-formatter (v1.2.17): Loading from cache
  - Installing doctrine/doctrine-bundle (1.11.2): Loading from cache
  - Installing doctrine/data-fixtures (v1.3.1): Loading from cache
  - Installing doctrine/doctrine-fixtures-bundle (3.2.2): Loading from cache
  - Installing symfony/stopwatch (v4.2.10): Loading from cache
  - Installing zendframework/zend-eventmanager (3.2.1): Loading from cache
  - Installing zendframework/zend-code (3.3.1): Loading from cache
  - Installing ocramius/proxy-manager (2.1.1): Loading from cache
  - Installing doctrine/migrations (v2.1.0): Loading from cache
  - Installing egulias/email-validator (2.1.9): Loading from cache
  - Installing erusev/parsedown (1.7.3): Loading from cache
  - Installing willdurand/negotiation (v2.3.1): Loading from cache
  - Installing willdurand/jsonp-callback-validator (v1.1.0): Loading from cache
  - Installing symfony/templating (v4.2.10): Loading from cache
  - Installing symfony/inflector (v4.2.10): Loading from cache
  - Installing symfony/property-access (v4.2.10): Loading from cache
  - Installing symfony/security (v4.2.8): Loading from cache
  - Installing friendsofsymfony/rest-bundle (2.5.0): Loading from cache
  - Installing twig/twig (v2.11.3): Loading from cache
  - Installing symfony/validator (v4.2.10): Loading from cache
  - Installing symfony/twig-bridge (v4.2.10): Loading from cache
  - Installing symfony/twig-bundle (v4.2.10): Loading from cache
  - Installing symfony/security-bundle (v4.2.10): Loading from cache
  - Installing symfony/options-resolver (v4.2.10): Loading from cache
  - Installing symfony/intl (v4.2.10): Loading from cache
  - Installing symfony/polyfill-intl-icu (v1.11.0): Loading from cache
  - Installing symfony/form (v4.2.10): Loading from cache
  - Installing paragonie/random_compat (v2.0.18): Loading from cache
  - Installing friendsofsymfony/user-bundle (v2.1.2): Loading from cache
  - Installing fzaninotto/faker (v1.8.0): Loading from cache
  - Installing behat/transliterator (v1.2.0): Loading from cache
  - Installing gedmo/doctrine-extensions (v2.4.37): Loading from cache
  - Installing hoa/exception (1.17.01.16): Loading from cache
  - Installing hoa/consistency (1.17.05.02): Loading from cache
  - Installing hoa/event (1.17.01.13): Loading from cache
  - Installing hoa/visitor (2.17.01.16): Loading from cache
  - Installing hoa/ustring (4.17.01.16): Loading from cache
  - Installing hoa/protocol (1.17.01.14): Loading from cache
  - Installing hoa/zformat (1.17.01.10): Loading from cache
  - Installing hoa/iterator (2.17.01.10): Loading from cache
  - Installing hoa/compiler (3.17.08.08): Loading from cache
  - Installing hoa/math (1.17.05.16): Loading from cache
  - Installing hoa/regex (1.17.01.13): Loading from cache
  - Installing hoa/stream (1.17.02.21): Loading from cache
  - Installing hoa/file (1.17.07.11): Loading from cache
  - Installing jms/metadata (2.0.0): Loading from cache
  - Installing jms/serializer (3.1.1): Loading from cache
  - Installing jms/serializer-bundle (3.4.1): Loading from cache
  - Installing kevinpapst/adminlte-bundle (2.8.3): Loading from cache
  - Installing setasign/fpdi (1.6.2): Loading from cache
  - Installing myclabs/deep-copy (1.9.1): Loading from cache
  - Installing mpdf/mpdf (v7.1.9): Loading from cache
  - Installing zircote/swagger-php (2.0.14): Loading from cache
  - Installing symfony/property-info (v4.2.10): Loading from cache
  - Installing webmozart/assert (1.4.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.3.1): Loading from cache
  - Installing exsyst/swagger (v0.4.1): Loading from cache
  - Installing nelmio/api-doc-bundle (v3.4.0): Loading from cache
  - Installing nelmio/cors-bundle (1.5.6): Loading from cache
  - Installing pclzip/pclzip (2.8.2): Loading from cache
  - Installing markbaker/matrix (1.1.4): Loading from cache
  - Installing markbaker/complex (1.4.7): Loading from cache
  - Installing phpoffice/phpspreadsheet (1.8.1): Loading from cache
  - Installing zendframework/zend-escaper (2.6.0): Loading from cache
  - Installing phpoffice/common (0.2.9): Loading from cache
  - Installing phpoffice/phpword (0.15.0): Loading from cache
  - Installing sensio/framework-extra-bundle (v5.3.1): Loading from cache
  - Installing symfony/polyfill-php72 (v1.11.0): Loading from cache
  - Installing symfony/var-dumper (v4.2.10): Loading from cache
  - Installing symfony/web-profiler-bundle (v4.2.10): Loading from cache
  - Installing symfony/profiler-pack (v1.0.4): Loading from cache
  - Installing monolog/monolog (1.24.0): Loading from cache
  - Installing symfony/monolog-bridge (v4.2.10): Loading from cache
  - Installing symfony/monolog-bundle (v3.4.0): Loading from cache
  - Installing symfony/debug-bundle (v4.2.10): Loading from cache
  - Installing symfony/yaml (v4.2.10): Loading from cache
  - Installing easycorp/easy-log-handler (v1.0.7): Loading from cache
  - Installing symfony/debug-pack (v1.0.7): Loading from cache
  - Installing symfony/dotenv (v4.2.10): Loading from cache
  - Installing symfony/expression-language (v4.2.10): Loading from cache
  - Installing nikic/php-parser (v4.2.2): Loading from cache
  - Installing symfony/maker-bundle (v1.11.6): Loading from cache
  - Installing doctrine/doctrine-migrations-bundle (v2.0.0): Loading from cache
  - Installing symfony/orm-pack (v1.0.6): Loading from cache
  - Installing symfony/polyfill-intl-idn (v1.11.0): Loading from cache
  - Installing symfony/serializer (v4.2.10): Loading from cache
  - Installing swiftmailer/swiftmailer (v6.2.1): Loading from cache
  - Installing symfony/swiftmailer-bundle (v3.2.8): Loading from cache
  - Installing symfony/process (v4.2.10): Loading from cache
  - Installing symfony/web-server-bundle (v4.2.10): Loading from cache
  - Installing symfony/asset (v4.2.10): Loading from cache
  - Installing symfony/webpack-encore-bundle (v1.6.2): Loading from cache
  - Installing twig/extensions (v1.5.4): Loading from cache
  - Installing symfony/translation (v4.2.10): Loading from cache
  - Installing pagerfanta/pagerfanta (v2.1.2): Loading from cache
  - Installing white-october/pagerfanta-bundle (v1.2.4): Loading from cache
Generating optimized autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  During class fetch: Uncaught ReflectionException: Class Symfony\Component\Security\Core\Authentication\Provider\UserAuthenticationProvider not found in /opt/kimai2/src/Ldap/LdapAuthenticationProvider.php:26
!!  Stack trace:
!!  #0 /opt/kimai2/vendor/composer/ClassLoader.php(444): include('/opt/kimai2/src...')
!!  #1 /opt/kimai2/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/opt/kimai2/ven...')
!!  #2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Ldap\\LdapAu...')
!!  #3 [internal function]: spl_autoload_call('App\\Ldap\\LdapAu...')
!!  #4 /opt/kimai2/vendor/symfony/config/Resource/ClassExistenceResource.php(76): class_exists('App\\Ldap\\LdapAu...')
!!  #5 /opt/kimai2/vendor/symfony/dependency-injection/ContainerBuilder.php(353): Symfony\Component\Config\Resource\ClassExistenceResource->isFresh(0)
!!  #6 /opt/kimai2/vendor/symfony/dependency-injection/Loader/FileLoader.php(151): Symfony\Component\DependencyInjection\ContainerBuilder->getReflectionClass('App\\Ldap\\LdapAu...')
!!  #7 /opt/kimai2/vendor in /opt/kimai2/src/Ldap/LdapAuthenticationProvider.php on line 26
!!
Script @auto-scripts was called via post-install-cmd

```

**To Reproduce**
1. Do a fresh install and run `composer install --no-dev --optimize-autoloader`

**Additional context**
 - Kimai version 1.0.1 (fresh git clone)
 - PHP version 7.3.7

**Comment by kevinpapst** [comment]
Its working on many systems, so thats a local issue.
Are you sure that `php -v` shows `7.3.7`?

**Comment by Mikesch-mp** [comment]
yes :)

php -v
PHP 7.3.7 (cli) (built: Jul  3 2019 11:30:22) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.7, Copyright (c) 1998-2018 Zend Technologies

**Comment by Mikesch-mp** [comment]
Os is latest CentOS 7

**Comment by kevinpapst** [comment]
Have you tried clearing the cache again? 
Have you tried running bin/console ?

**Comment by Mikesch-mp** [comment]
Yes all, ended in copying files from my other installed instance and then it works.

**Comment by kevinpapst** [comment]
Something strange is going on in your server ;-) or there is a problem with a specific PHP setup which I just can't find out.

Maybe updating to the latest Symfony version helps (which I plan for the next release).

**Comment by kevinpapst** [comment]
Hm, now when I look again, its is a class from the Symfony security bundle `Symfony\Component\Security` ... so a problem a bit like last time.

**Comment by Mikesch-mp** [comment]
Iam just using PHP from remi repository, nothign special.

**Comment by Mikesch-mp** [comment]
I found the problem. Its was a old version of composer (1.7.2) and not the lates version.

**Comment by kevinpapst** [comment]
Oh, that's interesting feedback. Didn't know that composer could cause such an issue.
Closing as fixed :-)
